{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Pulzone%2C_Scipione_-_Cristina_di_Lorena%2C_granduchessa_di_Toscana_-_1590.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Frans_Hals_-_Portrait_of_a_lady_with_a_landscape_background.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/03/Katharina_von_Mulinen_by_Samuel_Hoffman_1591-1648.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Ana_de_Austria2.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Frans_Pourbus_%28II%29_-_Portrait_of_Marie_de_M%C3%A9dicis_-_WGA18242.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Studio_of_Michiel_Jansz._van_Miereveldt_Elizabeth_Stuart_Queen_of_Bohemia.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/10/Marcus_Gheeraerts_Princess_Elizabeth_Stuart_1612.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/22/Pourbus%2C_Frans_-_Portrait_of_Maria_de%27_Medici%2C_Queen_of_France_%28Galleria_Palatina%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6d/MariadeMedici06.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0c/MariadeMedici06_%28cropped%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Elisabeth_Harnister-1611-f3688961.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/2e/Mus%C3%A9e_historique_de_Strasbourg-Elisabeth_Harnister-1611.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Kristina%2C_1573-1625%2C_drottning_av_Sverige_prinsessa_av_Holstein-Gottorp_-_Nationalmuseum_-_15095.tif"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Aartshertogin_Isabella_Rubens.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d6/M%C3%A5lning._Portr%C3%A4tt%2C_Katarina_Gyllenstierna_-_Skoklosters_slott_-_87719.tif"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Margarita_Aldobrandini%2C_Duchess_of_Parma_by_Bartolome_Gonzalez%2C_held_in_the_Hermitage_collection.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/13/Marie_Th%C3%A9r%C3%A8se_de_Bourbon_%281666-1732%29%2C_Mignard.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Ulrika_Eleonora_the_Elder_%281656-1693%29%2C_Princess_of_Denmark%2C_Queen_of_Sweden_-_Nationalmuseum_-_16076.tif"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Mary_of_Modena_Kneller.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Cleophea_Lavater_1686.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Rigaud_mariecadenne.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/49/Dorothea_von_Schleswig-Holstein-Sonderburg-Gl%C3%BCcksburg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Nicolaes_Maes_-_Portret_van_Catharina_Dierquens.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/34/Gobert_-_Mademoiselle_de_Blois%2C_princesse_de_Conti_-_Prado.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/34/Eleonore_of_Pfalz_Neuburg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/85/Portrait_of_a_Woman_Dressed_as_a_Huntress_by_Ferdinance_Bol.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Full_portrait_of_Marie_Anne_de_Bourbon_%281666-1739%29_by_Fran%C3%A7ois_de_Troy.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Jan_de_Baen_-_Portrait_of_a_Man_%28Likeness_of_an_Aristcrat%29_-_O_4695_-_Slovak_National_Gallery.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/44/Nicolaes_Maes_-_Portrait_of_a_Young_Woman_-_WGA13825.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Mary_of_Modena_when_Duchess_of_York_-_Verelst_c._1675.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Musscher_viola.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Marie_Jeanne_Baptiste_of_Savoy_as_a_widow_with_the_Savoyard_crown_behind_her_by_an_unknown_painter_%28full%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Maria_Anna_Wielopolska.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Slingelandt_Young_lady_with_a_rose.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/09/Henriette_Adelaide_of_Savoy_%28Electress_of_Bavaria%29_in_armour.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Netscher_C._Bicker%40Nieders._Landesmuseum20160811_%282%29.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Mary_of_Modena_Lely.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Frans_van_Mieris_d._%C3%84._003.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/33/Frans_van_mieris-dama-thyssen.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Palamedes_-_portrait_de_femme_en_Granida.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/13/HortenseManciniGodfreyKneller.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Schultz_Eleonora_Wi%C5%9Bniowiecka.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Portrait_of_Mary_Wilbraham.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Katarina_Elizabeta_grofica_Auersperg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Wilhelmine-Ernestine_de_Danemark%2C_duchesse_de_Bavi%C3%A8re.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/65/Gryzelda_Wi%C5%9Bniowiecka.jpeg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Duchess_Marie_Jeanne_of_Savoy_some_time_after_her_marriage_holding_the_Savoyard_crown_by_an_unknown_artist.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Benedicta_Henrietta%2C_Duchess_of_Brunswick-L%C3%BCneberg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/1d/Henriette_of_England_holding_a_portrait_of_her_husband_in_circa_1662_by_Netscher_Th%C3%A9odore.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Possibly_Lucretia_Boudaen_By_Van_Loo.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Tempel%2C_Abraham_van_den_-_Portrait_of_a_Woman.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/27/Portrait_of_a_woman_Abraham_Lambertz_van_den_Tempel.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/45/Beaubrun_Marie_Louise_Gonzaga.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/af/Portrait_of_Suzanna_Doublet-Huygens_by_Caspar_Netscher.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/79/Johannes_Mijtens_002.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Hendrick_Berckman_-_Portrait_of_Anna_van_Gelder_%281614-1685%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Geertruida_den_Dubbelde%2C_de_echtgenote_van_luitenant-admiraal_Aert_van_Nes%2C_by_Bartholomeus_van_der_Helst.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Aletta_van_Ravensberg_1668.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Retratodelareinamariana.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/27/Portrait-of-Francoise-Louise-de-la-Baume-le-Blanc-xx-Claude-Lefebvre.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/cd/LouiseDeLaValliere01.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/21/Henriette_von_Zuilestein_als_Diana_%28Hanneman%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d5/Mytens_-_Henrietta_of_England.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Eleanor_Dutton.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/66/Maria_Teresa_Fajardo%2C_Duchess_of_Montalto.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/16/Klosterrostock-gerdes1665.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Krystyna_z_Komorowskich_Wielopolska.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/9a/1664_Strauch_Bildnis_einer_Dame_mit_Blumen_anagoria.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Janez_Fran%C4%8Di%C5%A1ek_Gladi%C4%8D_-_Katarina_Lukan%C4%8Di%C4%8D.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Jacoba_Bicker.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/75/Stuker%2C_Spring_2017%2C_Nr.2034-1.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Princess_Henrietta_of_England_%281644%E2%80%931670%29%2C_Duchess_of_Orl%C3%A9ans_by_Jan_de_Baen.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Anonymous_Anna_Tworkowska.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/The_Grand_Duke_Ferdinand_II_of_Tuscany_and_his_Wife.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/76/Justus_Sustermans_004.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/12/Jan_Mytens_-_Portrait_of_a_Woman_-_79.PA.156_-_J._Paul_Getty_Museum.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/45/Painting_of_Margherita_Yolanda_di_Savoia_while_Duchess_of_Parma_by_an_unknown_artist.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Undated_portrait_of_La_Grande_Mademoiselle_%28Anne_Marie_Louise_d%27Orl%C3%A9ans%2C_Duchess_of_Montpensier%29_by_a_member_of_the_School_of_Pierre_Mignard.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Portrait_painting_of_Fran%C3%A7oise_de_Rochechouart_%28Madame_de_Montespan%29_by_an_unknown_artist_%28at_the_Mus%C3%A9e_national_du_Ch%C3%A2teau_de_Versailles%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/5a/Pierre_Mignard_Claude_de_Vin_des_Oeillets.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/82/Olympia_Mancini%2C_1640-1708_-_Nationalmuseum_-_15843.tif"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/84/Olympia_Mancini_by_Pierre_Mignard_1700.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/31/LudmillaElisabethSchwarzburg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Infanta_Maria_Teresa_%281638-1683%2C_future_Queen_of_France%29_by_Juan_Carre%C3%B1o_de_Miranda.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/20/Catherine_of_Braganza.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Anne_de_La_Grange-Trianon%2C_comtesse_de_Frontenac.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/1642_M.Henriette.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Lely_-_Diana%2C_Countess_Of_Ailesbury.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Elizabeth_Claypole_by_John_Michael_Wright.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Beaubrun_Portrait_of_a_lady.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/95/Retrato_de_la_reina_Mariana_de_Austria%2C_possibly_by_studio_of_Diego_Vel%C3%A1zquez.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/29/Portrait_of_Susanna_van_Baerle_%281622-1674%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Diego_Vel%C3%A1zquez_067.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Portrait_of_David_Teniers.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/49/Ebba_Sparre.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Vittoria_della_Rovere_%28So-called_portrait_of_Marguerite_Louise_d%27Orl%C3%A9ans%29_-_Alte_Pinakothe.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/92/Elizabeth_Percy.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Sustermans%2C_Justus_-_Official_portrait_of_Vittoria_della_Rovere_as_Grand_Duchess_of_Tuscany.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Princess_Enrichetta_Adelaide_of_Savoy_with_the_Bavarian_Electoral_crown_in_the_background_by_an_unknown_artist.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Orl%C3%A9ans_-_mus%C3%A9e_d%27histoire_%2807%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/68/Honthorst_Roodere.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Gerard_van_Honthorst_-_Margareta_Maria_de_Roodere_and_Her_Parents_-_WGA11679.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/59/David_Beck_-_Queen_Christina_-_KMSsp288_-_Statens_Museum_for_Kunst.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Anonymous_Portrait_of_a_lady_in_a_black_dress_with_a_fan.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Anonymous_Portrait_of_Helena_Opali%C5%84ska_%28detail%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/60/Frans_Hals_-_Isabella_Coymans_-_WGA11158.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Louise_Henriette_von_Oranien%2C_Kurf%C3%BCrstin_von_Brandenburg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6d/Frans_Hals_-_Portret_van_een_vrouw.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/65/Frans_Hals_-_Portret_van_een_vrouw_%28c.1650%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Charlotte_de_Hesse-Cassel%2C_Electrice_de_Baviere.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/fb/Amalia_van_Solms_%28Gerard_van_Honthorst%2C_1650%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/95/Bartholomeus_van_der_Helst_-_Frau_in_schwarzer_Atlasrobe.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/74/KatharinaCharlottePfalzZweibrNeuburg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Rembrandt_-_Portrait_of_a_woman_holding_a_fan_and_the_back_of_a_chair.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Beaubrun%2C_circle_of_-_Anne_of_Austria%2C_Alte_Pinakothek.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/79/Bol_Queen_of_Poland.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Ferdinand_Bol_-_Portrait_of_an_Unknown_Woman.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/76/Joachim_von_Sandrart_-_Erzherzogin_Maria_Anna_%281610-1665%29%2C_Kurf%C3%BCrstin_von_Bayern.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/50/Frans_Hals_105_WGA_version.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/56/Anna_Rosina_Marquart.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Jan_Daemen_Cool_001.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/66/Arnold_van_Ravesteyn_-_portrait_of_a_lady_holding_an_orange.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/57/La_Grande_Mademoiselle_by_Louis_Ferdinand_Elle.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Anonymous_Portrait_of_Jadwiga_Rogali%C5%84ska_%28detail%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/20/Justus_Sustermans_055.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Donna_olimpia_maidalchini.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Cosimo_ii_de%27_medici_adn_two.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Bildnis_Agneta_K%C3%B6ler_Michael_Conrad_Hirt_%281613%29%2C_nach_1640.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Anne_Marie_Louise_d%27Orl%C3%A9ans%2C_La_Grande_Mademoiselle_par_Gilbert_de_Seve.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Gerolamo_Forabosco_04.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Lucy_Percy_van_Dyck_2.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/91/Nicolas_Regnier_001.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/55/Dirck_Santvoort_-_Portrait_of_a_Lady_-_Google_Art_Project.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/23/Vliet_Woman_with_a_book.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Elizabeth_Hext.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/c6/Maria_Anna_of_Austria_-_Alte_Pinakothek%2C_2474.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/16/Frans_Luycx_007.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/87/Claudia_de%27_Medici_in_1635_by_Franz_Luycx.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Claudia_de%27_Medici%2C_Archduchess_of_Austria_in_circa_1640_by_Franz_Luycx.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Marguerite_de_Lorraine%2C_Madame%2C_duchesse_d%27Orl%C3%A9ans%2C_by_Anthony_van_Dyck.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/74/Anthony_van_Dyck_-_Portrait_of_a_Lady_-_WGA07402.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Sir_Anthony_van_Dyck_-_Lady_Dacre_-_Google_Art_Project.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Henrietta_Maria_by_Sir_Anthony_Van_Dyck.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/90/1632_van_Mierevelt_Bildnis_einer_Dame_anagoria.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Retrato_de_la_reina_Isabel_de_Borb%C3%B3n%2C_by_Diego_Vel%C3%A1zquez.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Maria_Salom%C3%A9_Bresier-1632-f3672257.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Diego_Vel%C3%A1zquez_069.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d0/HenriettaMariaofFrance03.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/95/HenriettaMariaofFrance03_%28cropped%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e9/Luisa_Francisca_de_Guzm%C3%A1n_y_Medina_Sidonia_atribuible_a_Alonso_Cano.png"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/45/Flinck_young_woman.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Anthonis_van_Dyck_037.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Anthonis_van_Dyck_018_%28d%C3%A9tail%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cornelis_de_Vos_%281585-1651%29_-_Portret_van_een_dame_%281630%29_-_Sevilla_Bellas_Artes_22-03-2011_12-03-44.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Justus_Sustermans_011.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b8/Justus_Sustermans_-_Anna_de%27_Medici%2C_wife_of_archduke_Ferdinand_Charles_of_Austria.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Anthonis_van_Dyck_021.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/FerdinandII.T%C3%B6chter.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/af/Anthony_van_Dyck_-_Portrait_of_Genevi%C3%A8ve_d%27Urf%C3%A9_Duchess_of_Croy_NGS_NG_1944.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Anthonis_van_Dyck_086.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b6/Maria_Jorisdr_Pijnaecker_%281599-1678%29%2C_by_Willem_Willemsz_van_der_Vliet_%28circa_1584-1642%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/Ana_Magdalena%2C_vojvodinja_v_M%C3%BCnsterbergu_%281626%29.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Peter_Paul_Rubens_186.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Rubens%2C_Ritratto_dell%27infanta_Isabella_Clara_Eugenia_di_Spagna_in_abito_di_clarissa.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Peter_Paul_Rubens_-_Portrait_of_Infanta_Clara_Eugenia%2C_Governess_of_the_Netherlands_-_WGA20363.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/36/Attributed_to_Pieter_Claesz._Soutman_001.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/16/P._Moreelse_Emerentia_van_Ravenswaey_1625.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/06/Pieter_Claesz._Soutman_-_Portrait_of_a_Woman.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/82/M%C3%B6ller_Lady_with_a_rose.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/A_Lady_and_Her_Two_Children_1624.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Justus_Sustermans_005.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Elizabeth_of_France_by_Frans_Pourbus.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/63/Rodrigo_de_Villandrando_-_Isabel_of_France_-_WGA25100.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/05/Juan_Pantoja_de_la_Cruz_011.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/82/Maria_Eleonora_of_Brandenburg.JPG"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/86/Maria_Eleonora_%281599-1655%29%2C_Princess_of_Brandenburg%2C_Queen_of_Sweden_-_Nationalmuseum_-_35091.tif"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Salomon_Mesdach_001.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Portrait_of_Anne_of_Austria.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/64/Frans_Hals_045.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/58/Bartolom%C3%A9_Gonz%C3%A1lez_y_Serrano_-_Portrait_of_Margarita_Aldobrandini%2C_Duchess_of_Parma_-_WGA9751.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/e/e1/William_Larkin_circle_of_Portrait_of_a_Lady.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/14/DorotheaSibylleBrandBrieg.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Rubens89.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/59/Margaret_of_austria_1609.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/5/52/Bartolom%C3%A9_Gonz%C3%A1lez_y_Serrano_-_Queen_Margarita_of_Austria_-_WGA9753.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Juan_Pantoja_de_la_Cruz_018.jpeg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Juan_Pantoja_de_la_Cruz_017.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Marina_mniszek.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Jan-Kraeck%2C-called-Giovanni-Caracca_Maria_Apollonia_di_Savoia.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/14/Lucy-lady-reynell-of-ford_med.jpeg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Juan_Pantoja_de_la_Cruz_007.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/9/92/Frans_Pourbus_d._J._005.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Santi_di_Tito%2C_Ritratto_di_Cristina_di_Lorena.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Christine_of_Lorraine_Medici3.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Frans_Pourbus_d._J._004.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/0/09/1589_Magdalena.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Marcus_Gheeraerts_the_Younger_Lady_Scudamore.png"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/1/11/Portr%C3%A6t_af_en_ung_dame.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Federico_Barocci%2C_Quintilia_Fischieri%2C_1600.jpg"}
{"target_url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Anne_of_Austria%2C_Consort_of_Emperor_Mathias_%28Gaspar_de_Crayer%29_-_Nationalmuseum_-_17411.tif"}
